name: 'Continuous Integration'

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código fuente
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t gcr.io/mlechallenge/mle_challenge_image .
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.GCP_SA_KEY}}

    - name: Login en el registro de Google Cloud Container
      run: gcloud auth configure-docker

    - name: Push Docker image a Google Cloud
      run: |
        docker push gcr.io/mlechallenge/mle_challenge_image
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.GCP_SA_KEY}}
